import { describe, it, expect } from "vitest";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

describe("static assets on disk", () => {
  it("关键美术文件存在且非空路径", () => {
    const files = [
      "public/assets/bg/menu_bg.jpg",
      "public/assets/bg/shop_bg.jpg",
      "public/assets/promo/cover.jpg",
      "public/assets/ui/vessels_sheet.jpg",
      "public/assets/audio/sfx_click.wav",
      "public/assets/audio/bgm_menu.wav",
      "public/assets/audio/LICENSE.txt",
      "public/assets/ui/order_board.jpg",
      "public/assets/ui/vessels_display.jpg",
      "public/assets/promo/keeper.jpg",
      "public/assets/bg/day_complete.jpg",
      "public/assets/ui/codex_empty.jpg",
      "public/assets/ui/tea_counter.jpg",
      "public/assets/decor/season_spring.jpg",
      "public/assets/bg/night_window.jpg",
      "public/assets/ui/corner_flourish.jpg",
      "public/assets/ui/doorbell.jpg",
      "public/assets/bg/rain_window.jpg",
      "public/assets/ui/shelf_display.jpg",
      "public/assets/ui/gift_station.jpg",
      "public/assets/ui/tutorial_book.jpg",
      "public/assets/ui/letter_seal.jpg",
      "public/assets/ui/closed_sign.jpg",
      "public/assets/decor/twin_lanterns.jpg",
      "public/assets/promo/guest_silhouette.jpg",
      "public/assets/ui/tip_jar.jpg",
      "public/assets/decor/morning_dew.jpg",
      "public/assets/bg/revisit_door.jpg",
      "public/assets/bg/puddle_glow.jpg",
      "public/assets/bg/half_window.jpg",
      "public/assets/ui/day_calendar.jpg",
      "public/assets/ui/storybooks.jpg",
      "public/assets/bg/evening_market.jpg",
      "public/assets/promo/full_moon.jpg",
      "public/assets/bg/street_lamp.jpg",
      "public/assets/ui/progress_ribbon.jpg",
      "public/assets/ui/paper_stamp.jpg",
      "public/assets/bg/wind_curtain.jpg",
      "public/assets/decor/signpost.jpg",
      "public/assets/ui/heart_charm.jpg",
      "public/assets/ui/quality_seal.jpg",
      "public/assets/ui/tea_tray.jpg",
      "public/assets/bg/rain_awning.jpg",
      "public/assets/ui/intensity_meter.jpg",
      "public/assets/decor/soft_blanket.jpg",
      "public/assets/bg/forty_lanterns.jpg",
      "public/assets/ui/sugar_bowl.jpg",
      "public/assets/ui/gift_tag.jpg",
      "public/assets/ui/fountain_pen.jpg",
      "public/assets/ui/journal_page.jpg",
      "public/assets/ui/chalkboard.jpg",
      "public/assets/ui/circulation_log.jpg",
      "public/assets/ui/guest_notebook.jpg",
      "public/assets/ui/match_abacus.jpg",
      "public/assets/ui/unlock_medal.jpg",
      "public/assets/ui/favor_board.jpg",
      "public/assets/ui/warmth_jar.jpg",
      "public/assets/ui/welcome_bell.jpg",
      "public/assets/bg/warmth_corner.jpg",
      "public/assets/promo/guest_a.jpg",
      "public/assets/promo/guest_b.jpg",
      "public/assets/promo/guest_c.jpg",
      "public/assets/ui/order_counter.jpg",
      "public/assets/bg/night_rain_window.jpg",
      "public/assets/ui/shelf_craft.jpg",
      "public/assets/ui/tea_cup.jpg",
      "public/assets/ui/vessel_flower.jpg",
      "public/assets/ui/vessel_art.jpg",
      "public/assets/ui/vessel_music.jpg",
      "public/assets/ui/codex_scrap.jpg",
      "public/assets/ui/codex_ribbon.jpg",
      "public/assets/bg/menu_hero.jpg",
      "public/assets/ui/unlock_ribbon.jpg",
      "public/assets/decor/window_seat.jpg",
      "public/assets/ui/price_tag.jpg",
      "public/assets/promo/guest_d.jpg",
      "public/assets/decor/umbrella_stand.jpg",
      "public/assets/ui/moment_letter.jpg",
      "public/assets/bg/puddle_dusk.jpg",
      "public/assets/ui/writing_desk.jpg",
      "public/assets/ui/settings_knob.jpg",
      "public/assets/decor/paper_cranes.jpg",
      "public/assets/ui/tutorial_spread.jpg",
      "public/assets/ui/welcome_doorbell.jpg",
      "public/assets/bg/evening_lanterns.jpg",
      "public/assets/ui/gift_box.jpg",
      "public/assets/ui/ribbon_spools.jpg",
      "public/assets/promo/guest_e.jpg",
      "public/assets/ui/codex_catalog.jpg",
      "public/assets/ui/music_box.jpg",
      "public/assets/bg/rain_shop_awning.jpg",
      "public/assets/ui/save_drawer.jpg",
      "public/assets/ui/day_page.jpg",
      "public/assets/ui/twin_cups.jpg",
      "public/assets/decor/soft_suitcase.jpg",
      "public/assets/ui/paper_lantern.jpg",
      "public/assets/ui/guest_book.jpg",
      "public/assets/ui/spice_jars.jpg",
      "public/assets/ui/wind_chime.jpg",
      "public/assets/decor/shop_cat.jpg",
      "public/assets/ui/postcards.jpg",
      "public/assets/ui/shop_key.jpg",
      "public/assets/bg/shutters_light.jpg",
      "public/assets/ui/moon_calendar.jpg",
      "public/assets/bg/evening_window.jpg",
      "public/assets/ui/soft_compass.jpg",
      "public/assets/ui/street_map.jpg",
      "public/assets/ui/hourglass.jpg",
      "public/assets/ui/ink_seal.jpg",
      "public/assets/ui/vessel_tray.jpg",
      "public/assets/ui/soft_candle.jpg",
      "public/assets/ui/wish_tags.jpg",
      "public/assets/ui/rain_curtain.jpg",
      "public/assets/ui/steam_cup.jpg",
      "public/assets/decor/mint_pots.jpg",
      "public/assets/ui/rest_stool.jpg",
      "public/assets/ui/scent_sachet.jpg",
      "public/assets/decor/dried_bouquet.jpg",
      "public/assets/ui/coat_hooks.jpg",
      "public/assets/decor/soft_scarves.jpg",
      "public/assets/ui/reply_box.jpg",
      "public/assets/ui/stamp_tray.jpg",
      "public/assets/ui/linen_apron.jpg",
      "public/assets/ui/soft_cuffs.jpg",
      "public/assets/ui/soft_radio.jpg",
      "public/assets/ui/record_needle.jpg",
      "public/assets/ui/ink_well.jpg",
      "public/assets/ui/blotter_stack.jpg",
      "public/assets/ui/lace_curtain.jpg",
      "public/assets/bg/lace_light.jpg",
      "public/assets/ui/dew_doorbell.jpg",
      "public/assets/decor/wet_sill.jpg",
      "public/assets/ui/biscuit_tin.jpg",
      "public/assets/ui/sugar_spoon.jpg",
      "public/assets/ui/step_ladder.jpg",
      "public/assets/ui/high_shelf.jpg",
      "public/assets/ui/guest_mirror.jpg",
      "public/assets/ui/soft_cloth.jpg",
      "public/assets/ui/ribbon_spools_soft.jpg",
      "public/assets/ui/snip_thread_box.jpg",
      "public/assets/ui/door_mat.jpg",
      "public/assets/decor/shoe_box.jpg",
      "public/assets/ui/hand_soap.jpg",
      "public/assets/ui/soft_towel.jpg",
      "public/assets/ui/warm_kettle.jpg",
      "public/assets/ui/cup_lid.jpg",
      "public/assets/ui/bird_seed_jar.jpg",
      "public/assets/decor/seed_dish.jpg",
      "public/assets/ui/soft_broom.jpg",
      "public/assets/ui/dustpan.jpg",
      "public/assets/ui/picture_frame.jpg",
      "public/assets/ui/hanging_cord.jpg",
      "public/assets/ui/cork_board.jpg",
      "public/assets/ui/push_pin_tin.jpg",
      "public/assets/ui/copper_thimble.jpg",
      "public/assets/ui/pincushion.jpg",
      "public/assets/ui/button_box.jpg",
      "public/assets/ui/soft_tape.jpg",
      "public/assets/ui/thread_spool.jpg",
      "public/assets/ui/beeswax_brick.jpg",
      "public/assets/ui/soft_shears.jpg",
      "public/assets/ui/snip_dish.jpg",
      "public/assets/ui/pattern_paper.jpg",
      "public/assets/ui/chalk_wheel.jpg",
      "public/assets/ui/soft_iron.jpg",
      "public/assets/ui/press_pad.jpg",
      "public/assets/ui/darning_egg.jpg",
      "public/assets/ui/needle_book.jpg",
      "public/assets/ui/fabric_clips.jpg",
      "public/assets/ui/marking_pen.jpg",
      "public/assets/ui/seam_ripper.jpg",
      "public/assets/ui/emery_bag.jpg",
      "public/assets/ui/tailor_ham.jpg",
      "public/assets/ui/sleeve_board.jpg",
      "public/assets/ui/stitching_awl.jpg",
      "public/assets/ui/bone_folder.jpg",
      "public/assets/ui/book_press.jpg",
      "public/assets/ui/weight_bar.jpg",
      "public/assets/ui/binding_thread.jpg",
      "public/assets/ui/sewing_needle.jpg",
      "public/assets/ui/bookcloth.jpg",
      "public/assets/ui/spine_strip.jpg",
      "public/assets/ui/endpaper.jpg",
      "public/assets/ui/headband_ribbon.jpg",
      "public/assets/ui/paste_pot.jpg",
      "public/assets/ui/paste_brush.jpg",
      "public/assets/ui/cutting_mat.jpg",
      "public/assets/ui/straight_ruler.jpg",
      "public/assets/ui/craft_knife.jpg",
      "public/assets/ui/safety_ruler.jpg",
      "public/assets/ui/corner_rounder.jpg",
      "public/assets/ui/corner_guards.jpg",
      "public/assets/ui/eyelets.jpg",
      "public/assets/ui/eyelet_punch.jpg",
      "public/assets/ui/sealing_wax.jpg",
      "public/assets/ui/wax_spoon.jpg",
      "public/assets/ui/seal_stamp.jpg",
      "public/assets/ui/ink_pad.jpg",
      "public/assets/ui/bookmark_ribbon.jpg",
      "public/assets/ui/page_dogear.jpg",
      "public/assets/ui/shop_ledger.jpg",
      "public/assets/ui/soft_pencil.jpg",
      "public/assets/ui/receipt_slip.jpg",
      "public/assets/ui/round_stamp.jpg",
      "public/assets/ui/kraft_bag.jpg",
      "public/assets/ui/hemp_twine.jpg",
      "public/assets/ui/warm_tag_card.jpg",
      "public/assets/ui/fine_string.jpg",
      "public/assets/ui/change_dish.jpg",
      "public/assets/ui/palm_kerchief.jpg",
      "public/assets/ui/key_tray.jpg",
      "public/assets/ui/closing_lamp.jpg",
      "public/assets/ui/morning_cloth.jpg",
      "public/assets/ui/sill_vase.jpg",
      "public/assets/ui/umbrella_stand.jpg",
      "public/assets/ui/door_mat.jpg",
      "public/assets/ui/guest_log.jpg",
      "public/assets/ui/soft_eraser.jpg",
      "public/assets/ui/wait_cushion.jpg",
      "public/assets/ui/warm_water_cup.jpg",
      "public/assets/ui/desk_calendar.jpg",
      "public/assets/ui/today_sticker.jpg",
      "public/assets/ui/sticky_pad.jpg",
      "public/assets/ui/fine_pen.jpg",
      "public/assets/ui/paper_clips.jpg",
      "public/assets/ui/mini_tray.jpg",
      "public/assets/ui/ink_well.jpg",
      "public/assets/ui/blotting_paper.jpg",
      "public/assets/ui/wooden_bookend.jpg",
      "public/assets/ui/page_weight.jpg",
      "public/assets/ui/paper_shade.jpg",
      "public/assets/ui/cord_switch.jpg",
    ];














    for (const f of files) {
      const p = resolve(root, f);
      expect(existsSync(p), `missing ${f}`).toBe(true);
    }
  });

  it("入口与核心模块存在", () => {
    for (const f of ["index.html", "src/main.ts", "src/core/game.ts", "src/ui/app.ts"]) {
      expect(existsSync(resolve(root, f)), f).toBe(true);
    }
  });
});
