import { describe, it, expect } from "vitest";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

describe("static assets on disk", () => {
  it("关键美术文件存在且非空路径", () => {
    const files = [
      "public/assets/bg/menu_bg.jpg",
      "public/assets/bg/shop_bg.jpg",
      "public/assets/promo/cover.jpg",
      "public/assets/ui/vessels_sheet.jpg",
      "public/assets/audio/sfx_click.wav",
      "public/assets/audio/bgm_menu.wav",
      "public/assets/audio/LICENSE.txt",
      "public/assets/ui/order_board.jpg",
      "public/assets/ui/vessels_display.jpg",
      "public/assets/promo/keeper.jpg",
      "public/assets/bg/day_complete.jpg",
      "public/assets/ui/codex_empty.jpg",
      "public/assets/ui/tea_counter.jpg",
      "public/assets/decor/season_spring.jpg",
      "public/assets/bg/night_window.jpg",
      "public/assets/ui/corner_flourish.jpg",
      "public/assets/ui/doorbell.jpg",
      "public/assets/bg/rain_window.jpg",
      "public/assets/ui/shelf_display.jpg",
      "public/assets/ui/gift_station.jpg",
      "public/assets/ui/tutorial_book.jpg",
      "public/assets/ui/letter_seal.jpg",
      "public/assets/ui/closed_sign.jpg",
      "public/assets/decor/twin_lanterns.jpg",
      "public/assets/promo/guest_silhouette.jpg",
      "public/assets/ui/tip_jar.jpg",
      "public/assets/decor/morning_dew.jpg",
      "public/assets/bg/revisit_door.jpg",
      "public/assets/bg/puddle_glow.jpg",
      "public/assets/bg/half_window.jpg",
      "public/assets/ui/day_calendar.jpg",
      "public/assets/ui/storybooks.jpg",
      "public/assets/bg/evening_market.jpg",
      "public/assets/promo/full_moon.jpg",
      "public/assets/bg/street_lamp.jpg",
      "public/assets/ui/progress_ribbon.jpg",
      "public/assets/ui/paper_stamp.jpg",
      "public/assets/bg/wind_curtain.jpg",
      "public/assets/decor/signpost.jpg",
      "public/assets/ui/heart_charm.jpg",
      "public/assets/ui/quality_seal.jpg",
      "public/assets/ui/tea_tray.jpg",
      "public/assets/bg/rain_awning.jpg",
      "public/assets/ui/intensity_meter.jpg",
      "public/assets/decor/soft_blanket.jpg",
      "public/assets/bg/forty_lanterns.jpg",
      "public/assets/ui/sugar_bowl.jpg",
      "public/assets/ui/gift_tag.jpg",
      "public/assets/ui/fountain_pen.jpg",
      "public/assets/ui/journal_page.jpg",
      "public/assets/ui/chalkboard.jpg",
      "public/assets/ui/circulation_log.jpg",
      "public/assets/ui/guest_notebook.jpg",
      "public/assets/ui/match_abacus.jpg",
      "public/assets/ui/unlock_medal.jpg",
      "public/assets/ui/favor_board.jpg",
      "public/assets/ui/warmth_jar.jpg",
      "public/assets/ui/welcome_bell.jpg",
      "public/assets/bg/warmth_corner.jpg",
      "public/assets/promo/guest_a.jpg",
      "public/assets/promo/guest_b.jpg",
      "public/assets/promo/guest_c.jpg",
      "public/assets/ui/order_counter.jpg",
      "public/assets/bg/night_rain_window.jpg",
      "public/assets/ui/shelf_craft.jpg",
      "public/assets/ui/tea_cup.jpg",
      "public/assets/ui/vessel_flower.jpg",
      "public/assets/ui/vessel_art.jpg",
      "public/assets/ui/vessel_music.jpg",
      "public/assets/ui/codex_scrap.jpg",
      "public/assets/ui/codex_ribbon.jpg",
      "public/assets/bg/menu_hero.jpg",
      "public/assets/ui/unlock_ribbon.jpg",
      "public/assets/decor/window_seat.jpg",
      "public/assets/ui/price_tag.jpg",
      "public/assets/promo/guest_d.jpg",
      "public/assets/decor/umbrella_stand.jpg",
      "public/assets/ui/moment_letter.jpg",
      "public/assets/bg/puddle_dusk.jpg",
      "public/assets/ui/writing_desk.jpg",
      "public/assets/ui/settings_knob.jpg",
      "public/assets/decor/paper_cranes.jpg",
      "public/assets/ui/tutorial_spread.jpg",
      "public/assets/ui/welcome_doorbell.jpg",
      "public/assets/bg/evening_lanterns.jpg",
      "public/assets/ui/gift_box.jpg",
      "public/assets/ui/ribbon_spools.jpg",
      "public/assets/promo/guest_e.jpg",
      "public/assets/ui/codex_catalog.jpg",
      "public/assets/ui/music_box.jpg",
      "public/assets/bg/rain_shop_awning.jpg",
      "public/assets/ui/save_drawer.jpg",
      "public/assets/ui/day_page.jpg",
      "public/assets/ui/twin_cups.jpg",
      "public/assets/decor/soft_suitcase.jpg",
      "public/assets/ui/paper_lantern.jpg",
      "public/assets/ui/guest_book.jpg",
      "public/assets/ui/spice_jars.jpg",
      "public/assets/ui/wind_chime.jpg",
      "public/assets/decor/shop_cat.jpg",
      "public/assets/ui/postcards.jpg",
      "public/assets/ui/shop_key.jpg",
      "public/assets/bg/shutters_light.jpg",
      "public/assets/ui/moon_calendar.jpg",
      "public/assets/bg/evening_window.jpg",
      "public/assets/ui/soft_compass.jpg",
      "public/assets/ui/street_map.jpg",
      "public/assets/ui/hourglass.jpg",
      "public/assets/ui/ink_seal.jpg",
      "public/assets/ui/vessel_tray.jpg",
      "public/assets/ui/soft_candle.jpg",
      "public/assets/ui/wish_tags.jpg",
      "public/assets/ui/rain_curtain.jpg",
      "public/assets/ui/steam_cup.jpg",
      "public/assets/decor/mint_pots.jpg",
      "public/assets/ui/rest_stool.jpg",
      "public/assets/ui/scent_sachet.jpg",
      "public/assets/decor/dried_bouquet.jpg",
      "public/assets/ui/coat_hooks.jpg",
      "public/assets/decor/soft_scarves.jpg",
      "public/assets/ui/reply_box.jpg",
      "public/assets/ui/stamp_tray.jpg",
      "public/assets/ui/linen_apron.jpg",
      "public/assets/ui/soft_cuffs.jpg",
      "public/assets/ui/soft_radio.jpg",
      "public/assets/ui/record_needle.jpg",
      "public/assets/ui/ink_well.jpg",
      "public/assets/ui/blotter_stack.jpg",
      "public/assets/ui/lace_curtain.jpg",
      "public/assets/bg/lace_light.jpg",
      "public/assets/ui/dew_doorbell.jpg",
      "public/assets/decor/wet_sill.jpg",
      "public/assets/ui/biscuit_tin.jpg",
      "public/assets/ui/sugar_spoon.jpg",
      "public/assets/ui/step_ladder.jpg",
      "public/assets/ui/high_shelf.jpg",
      "public/assets/ui/guest_mirror.jpg",
      "public/assets/ui/soft_cloth.jpg",
      "public/assets/ui/ribbon_spools_soft.jpg",
      "public/assets/ui/snip_thread_box.jpg",
      "public/assets/ui/door_mat.jpg",
      "public/assets/decor/shoe_box.jpg",
      "public/assets/ui/hand_soap.jpg",
      "public/assets/ui/soft_towel.jpg",
      "public/assets/ui/warm_kettle.jpg",
      "public/assets/ui/cup_lid.jpg",
      "public/assets/ui/bird_seed_jar.jpg",
      "public/assets/decor/seed_dish.jpg",
      "public/assets/ui/soft_broom.jpg",
      "public/assets/ui/dustpan.jpg",
      "public/assets/ui/picture_frame.jpg",
      "public/assets/ui/hanging_cord.jpg",
      "public/assets/ui/cork_board.jpg",
      "public/assets/ui/push_pin_tin.jpg",
      "public/assets/ui/copper_thimble.jpg",
      "public/assets/ui/pincushion.jpg",
      "public/assets/ui/button_box.jpg",
      "public/assets/ui/soft_tape.jpg",
      "public/assets/ui/thread_spool.jpg",
      "public/assets/ui/beeswax_brick.jpg",
      "public/assets/ui/soft_shears.jpg",
      "public/assets/ui/snip_dish.jpg",
      "public/assets/ui/pattern_paper.jpg",
      "public/assets/ui/chalk_wheel.jpg",
      "public/assets/ui/soft_iron.jpg",
      "public/assets/ui/press_pad.jpg",
      "public/assets/ui/darning_egg.jpg",
      "public/assets/ui/needle_book.jpg",
      "public/assets/ui/fabric_clips.jpg",
      "public/assets/ui/marking_pen.jpg",
      "public/assets/ui/seam_ripper.jpg",
      "public/assets/ui/emery_bag.jpg",
      "public/assets/ui/tailor_ham.jpg",
      "public/assets/ui/sleeve_board.jpg",
      "public/assets/ui/stitching_awl.jpg",
      "public/assets/ui/bone_folder.jpg",
      "public/assets/ui/book_press.jpg",
      "public/assets/ui/weight_bar.jpg",
      "public/assets/ui/binding_thread.jpg",
      "public/assets/ui/sewing_needle.jpg",
      "public/assets/ui/bookcloth.jpg",
      "public/assets/ui/spine_strip.jpg",
      "public/assets/ui/endpaper.jpg",
      "public/assets/ui/headband_ribbon.jpg",
      "public/assets/ui/paste_pot.jpg",
      "public/assets/ui/paste_brush.jpg",
      "public/assets/ui/cutting_mat.jpg",
      "public/assets/ui/straight_ruler.jpg",
      "public/assets/ui/craft_knife.jpg",
      "public/assets/ui/safety_ruler.jpg",
      "public/assets/ui/corner_rounder.jpg",
      "public/assets/ui/corner_guards.jpg",
      "public/assets/ui/eyelets.jpg",
      "public/assets/ui/eyelet_punch.jpg",
      "public/assets/ui/sealing_wax.jpg",
      "public/assets/ui/wax_spoon.jpg",
      "public/assets/ui/seal_stamp.jpg",
      "public/assets/ui/ink_pad.jpg",
      "public/assets/ui/bookmark_ribbon.jpg",
      "public/assets/ui/page_dogear.jpg",
      "public/assets/ui/shop_ledger.jpg",
      "public/assets/ui/soft_pencil.jpg",
      "public/assets/ui/receipt_slip.jpg",
      "public/assets/ui/round_stamp.jpg",
      "public/assets/ui/kraft_bag.jpg",
      "public/assets/ui/hemp_twine.jpg",
      "public/assets/ui/warm_tag_card.jpg",
      "public/assets/ui/fine_string.jpg",
      "public/assets/ui/change_dish.jpg",
      "public/assets/ui/palm_kerchief.jpg",
      "public/assets/ui/key_tray.jpg",
      "public/assets/ui/closing_lamp.jpg",
      "public/assets/ui/morning_cloth.jpg",
      "public/assets/ui/sill_vase.jpg",
      "public/assets/ui/umbrella_stand.jpg",
      "public/assets/ui/door_mat.jpg",
      "public/assets/ui/guest_log.jpg",
      "public/assets/ui/soft_eraser.jpg",
      "public/assets/ui/wait_cushion.jpg",
      "public/assets/ui/warm_water_cup.jpg",
      "public/assets/ui/desk_calendar.jpg",
      "public/assets/ui/today_sticker.jpg",
      "public/assets/ui/sticky_pad.jpg",
      "public/assets/ui/fine_pen.jpg",
      "public/assets/ui/paper_clips.jpg",
      "public/assets/ui/mini_tray.jpg",
      "public/assets/ui/ink_well.jpg",
      "public/assets/ui/blotting_paper.jpg",
      "public/assets/ui/wooden_bookend.jpg",
      "public/assets/ui/page_weight.jpg",
      "public/assets/ui/paper_shade.jpg",
      "public/assets/ui/cord_switch.jpg",
      "public/assets/ui/tasting_spoon.jpg",
      "public/assets/ui/tasting_mat.jpg",
      "public/assets/ui/jar_tag.jpg",
      "public/assets/ui/fine_cotton.jpg",
      "public/assets/ui/blank_postcard.jpg",
      "public/assets/ui/stamp_box.jpg",
      "public/assets/ui/window_cushion.jpg",
      "public/assets/ui/sheer_curtain.jpg",
      "public/assets/ui/clay_pot.jpg",
      "public/assets/ui/watering_can.jpg",
      "public/assets/ui/cup_rest.jpg",
      "public/assets/ui/tea_cloth.jpg",
      "public/assets/ui/honey_jar.jpg",
      "public/assets/ui/wood_dipper.jpg",
      "public/assets/ui/milk_jug.jpg",
      "public/assets/ui/cream_spoon.jpg",
      "public/assets/ui/lemon_dish.jpg",
      "public/assets/ui/citrus_knife.jpg",
      "public/assets/ui/napkin_ring.jpg",
      "public/assets/ui/guest_napkin.jpg",
      "public/assets/ui/place_mat.jpg",
      "public/assets/ui/chopstick_rest.jpg",
      "public/assets/ui/soy_cruet.jpg",
      "public/assets/ui/vinegar_dish.jpg",
      "public/assets/ui/clay_lid.jpg",
      "public/assets/ui/wood_paddle.jpg",
      "public/assets/ui/oven_mitt.jpg",
      "public/assets/ui/bake_pad.jpg",
      "public/assets/ui/kitchen_hourglass.jpg",
      "public/assets/ui/soft_timer_bell.jpg",
      "public/assets/ui/flour_bin.jpg",
      "public/assets/ui/measure_cup.jpg",
      "public/assets/ui/mix_bowl.jpg",
      "public/assets/ui/wire_whisk.jpg",
      "public/assets/ui/rolling_pin.jpg",
      "public/assets/ui/dust_spoon.jpg",
      "public/assets/ui/dough_scraper.jpg",
      "public/assets/ui/bake_parchment.jpg",
      "public/assets/ui/cookie_cutter.jpg",
      "public/assets/ui/cooling_rack.jpg",
      "public/assets/ui/icing_bag.jpg",
      "public/assets/ui/sugar_sieve.jpg",
      "public/assets/ui/cookie_tin.jpg",
      "public/assets/ui/twist_tie.jpg",
      "public/assets/ui/recipe_card.jpg",
      "public/assets/ui/wood_clip.jpg",
      "public/assets/ui/oven_thermo.jpg",
      "public/assets/ui/timer_dial.jpg",
      "public/assets/ui/spice_jar.jpg",
      "public/assets/ui/wood_scoop.jpg",
      "public/assets/ui/stone_mortar.jpg",
      "public/assets/ui/wood_pestle.jpg",
      "public/assets/ui/herb_bundle.jpg",
      "public/assets/ui/hang_twine.jpg",
      "public/assets/ui/herb_oil_bottle.jpg",
      "public/assets/ui/glass_dropper.jpg",
      "public/assets/ui/salve_tin.jpg",
      "public/assets/ui/bamboo_spatula.jpg",
      "public/assets/ui/cotton_pad.jpg",
      "public/assets/ui/gauze_roll.jpg",
      "public/assets/ui/rose_water_bottle.jpg",
      "public/assets/ui/linen_cloth.jpg",
      "public/assets/ui/soap_bar.jpg",
      "public/assets/ui/soap_dish.jpg",
      "public/assets/ui/lotion_bottle.jpg",
      "public/assets/ui/pump_cap.jpg",
      "public/assets/ui/bath_salt_jar.jpg",
      "public/assets/ui/shell_scoop.jpg",
      "public/assets/ui/diffuser_bottle.jpg",
      "public/assets/ui/rattan_reed.jpg",
      "public/assets/ui/tealight.jpg",
      "public/assets/ui/candle_snuffer.jpg",
      "public/assets/ui/matchbox.jpg",
      "public/assets/ui/matchstick.jpg",
      "public/assets/ui/paper_lantern.jpg",
      "public/assets/ui/lantern_shade.jpg",
      "public/assets/ui/sand_timer.jpg",
      "public/assets/ui/fine_sand.jpg",
      "public/assets/ui/pressed_mark.jpg",
      "public/assets/ui/silk_tail.jpg",
      "public/assets/ui/ceramic_pen_rest.jpg",
      "public/assets/ui/blot_sheet.jpg",
      "public/assets/ui/cream_envelope.jpg",
      "public/assets/ui/letter_opener.jpg",
      "public/assets/ui/desk_cal_block.jpg",
      "public/assets/ui/day_page_ribbon.jpg",
      "public/assets/ui/guest_cup.jpg",
      "public/assets/ui/linen_coaster.jpg",
      "public/assets/ui/brass_desk_bell.jpg",
      "public/assets/ui/felt_mallet.jpg",
      "public/assets/ui/soft_sign_book.jpg",
      "public/assets/ui/graphite_pencil.jpg",
      "public/assets/ui/soft_wool_scarf.jpg",
      "public/assets/ui/wood_coat_peg.jpg",
      "public/assets/ui/fold_umbrella.jpg",
      "public/assets/ui/ceramic_um_stand.jpg",
      "public/assets/ui/soft_mitten.jpg",
      "public/assets/ui/mitten_basket.jpg",
      "public/assets/ui/thermos_flask.jpg",
      "public/assets/ui/wool_sleeve.jpg",
      "public/assets/ui/soft_beanie.jpg",
      "public/assets/ui/wood_hat_form.jpg",
      "public/assets/ui/soft_slipper.jpg",
      "public/assets/ui/wood_shoe_tray.jpg",
      "public/assets/ui/soft_earmuff.jpg",
      "public/assets/ui/earmuff_peg.jpg",
      "public/assets/ui/fingerless_glove.jpg",
      "public/assets/ui/glove_dish.jpg",
      "public/assets/ui/knee_blanket.jpg",
      "public/assets/ui/blanket_board.jpg",
      "public/assets/ui/soft_eye_mask.jpg",
      "public/assets/ui/mask_pouch.jpg",
      "public/assets/ui/lavender_sachet.jpg",
      "public/assets/ui/sachet_dish.jpg",
      "public/assets/ui/beeswax_tin.jpg",
      "public/assets/ui/strike_strip.jpg",
      "public/assets/ui/soft_cloth_tape.jpg",
      "public/assets/ui/tape_wood_clip.jpg",
      "public/assets/ui/soft_button_tin.jpg",
      "public/assets/ui/button_scoop.jpg",
      "public/assets/ui/embroidery_hoop.jpg",
      "public/assets/ui/embroidery_floss.jpg",
      "public/assets/ui/cloth_weight.jpg",
      "public/assets/ui/paper_pattern.jpg",
      "public/assets/ui/rotary_cutter.jpg",
      "public/assets/ui/soft_cut_mat.jpg",
      "public/assets/ui/mini_steam_iron.jpg",
      "public/assets/ui/steam_press_cloth.jpg",
      "public/assets/ui/soft_tailor_chalk.jpg",
      "public/assets/ui/chalk_tray.jpg",
      "public/assets/ui/soft_pin_cushion.jpg",
      "public/assets/ui/straight_pins.jpg",
      "public/assets/ui/embro_snips.jpg",
      "public/assets/ui/snips_sheath.jpg",
      "public/assets/ui/mend_mushroom.jpg",
      "public/assets/ui/mend_yarn.jpg",
    ];











































    for (const f of files) {
      const p = resolve(root, f);
      expect(existsSync(p), `missing ${f}`).toBe(true);
    }
  });

  it("入口与核心模块存在", () => {
    for (const f of ["index.html", "src/main.ts", "src/core/game.ts", "src/ui/app.ts"]) {
      expect(existsSync(resolve(root, f)), f).toBe(true);
    }
  });
});
